"""
NACECA build script.

Pipeline:
  1. Concatenate all source modules in dependency order → src/_bundle.js
  2. Inline _bundle.js + styles.css into index.html → naceca.html (single-file build)

Dependency order matters because we use plain <script> globals (no ES modules).
This avoids requiring a webserver — naceca.html runs from any file:// URL.
"""

import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))  # works wherever the repo is checked out
SRC = os.path.join(ROOT, "src")
BUNDLE_OUT = os.path.join(SRC, "_bundle.js")
HTML_IN = os.path.join(ROOT, "index.html")
CSS_IN = os.path.join(ROOT, "styles.css")
HTML_OUT = os.path.join(ROOT, "naceca.html")
# NACECA_OUT_DIR=<dir> writes _bundle.js and naceca.html there instead (for parallel test builds);
# it also skips mirroring the music folder.
OUT_DIR = os.environ.get("NACECA_OUT_DIR")
if OUT_DIR:
    os.makedirs(OUT_DIR, exist_ok=True)
    BUNDLE_OUT = os.path.join(OUT_DIR, "_bundle.js")
    HTML_OUT = os.path.join(OUT_DIR, "naceca.html")

# Dependency order — config before systems, engine before scenes, scenes before flow.
LOAD_ORDER = [
    "_HEADER.js",
    "assets/_inline.js",
    "assets/_music_inline.js",
    "assets/_portraits_art.js",
    "config/missions.js",
    "config/skills.js",
    "config/dialogue.js",
    "config/puzzles.js",
    "config/casefile.js",
    "config/evidence_board.js",
    "systems/state.js",
    "systems/util.js",
    "beta/icons.js",
    "systems/state_save.js",
    "systems/audio.js",
    "systems/engine.js",
    "systems/characters.js",
    "systems/people_art_pass.js",
    "systems/npc_cast.js",
    "systems/traffic.js",
    "systems/pressure.js",
    "systems/settings.js",
    "systems/guidance.js",
    "systems/onboarding.js",
    "systems/progression.js",
    "systems/finale.js",
    "scenes/_common.js",
    "scenes/prologue.js",
    "scenes/hq.js",
    "scenes/market.js",
    "scenes/mansion.js",
    "scenes/checkpoint.js",
    "scenes/shrine.js",
    "scenes/asaba.js",
    "scenes/tower.js",
    "scenes/ekosodin.js",
    "systems/dialogue_system.js",
    "systems/puzzle_system.js",
    "systems/evidence.js",
    "systems/mission_flow.js",
    "systems/aftermath.js",
    "systems/mission_select.js",
    "systems/skill_tree.js",
    "systems/evidence_board.js",
    "systems/pause.js",
    "systems/boot.js",
    "systems/art_pass_v8.js",
    "main.js",
]

# v12 layer — appended as separate blocks just before </body>, after the bundle
V12_DIR = os.path.join(SRC, "v12")
V12_CSS = ["v12.css"]
V12_JS = ["v12_core.js", "v12_docs.js", "v12_ops.js", "v12_plan.js", "v12_finale.js",
          "v12_night.js", "v12_mem.js", "v12_street.js", "v12_hub.js", "v12_sound.js", "v12_car.js",
          "v12_daily.js", "v12_share.js", "v12_vo.js", "v12_pt.js", "v12_boot.js"]

# beta layer (friends-beta pass: wayfinding, chases, casework, paper UI) — after v12, so it wins
BETA_DIR = os.path.join(SRC, "beta")
BETA_CSS = ["paper.css", "wayfind.css", "board.css", "casework.css"]
BETA_JS = ["casework.js", "wayfind.js", "chase.js"]

def build_bundle():
    parts = []
    parts.append(
        "/* =========================================================================\n"
        "   NACECA · src/_bundle.js  (auto-generated by build.py — do not edit)\n"
        "   Source modules under config/, systems/, scenes/ — edit those instead.\n"
        "   ========================================================================= */\n\n"
    )
    for rel in LOAD_ORDER:
        path = os.path.join(SRC, rel)
        if not os.path.exists(path):
            print(f"  ! missing {rel}")
            continue
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        parts.append(f"\n/* ---------- {rel} ---------- */\n")
        parts.append(content)
        parts.append("\n")
    bundle = "".join(parts)
    with open(BUNDLE_OUT, "w", encoding="utf-8") as f:
        f.write(bundle)
    print(f"  bundle: {BUNDLE_OUT}  ({len(bundle):,} chars)")
    return bundle

def build_html(bundle):
    with open(HTML_IN, "r", encoding="utf-8") as f:
        html = f.read()
    with open(CSS_IN, "r", encoding="utf-8") as f:
        css = f.read()
    # Inline the CSS — replace the <link> with a <style> block
    html = re.sub(
        r'<link rel="stylesheet" href="styles\.css"\s*/?>',
        lambda m: f"<style>\n{css}\n</style>",
        html,
    )
    # Inline other local scripts (vendor loaders, generated art) as their own <script> blocks
    def _inline_local(m):
        p = os.path.join(ROOT, m.group(1))
        with open(p, "r", encoding="utf-8") as fh:
            return f"<script>\n{fh.read()}\n</script>"
    html = re.sub(r'<script src="(src/(?:vendor|assets)/[^"]+\.js)"></script>', _inline_local, html)
    # Inline the bundle — replace the <script src="src/_bundle.js"> with a <script>...</script>
    html = re.sub(
        r'<script src="src/_bundle\.js"></script>',
        lambda m: f"<script>\n{bundle}\n</script>",
        html,
    )
    # Append the v12 layer before </body>
    parts = []
    for name in V12_CSS:
        with open(os.path.join(V12_DIR, name), "r", encoding="utf-8") as fh:
            parts.append(f'<style id="{name[:-4]}">\n{fh.read()}\n</style>')
    for name in V12_JS:
        with open(os.path.join(V12_DIR, name), "r", encoding="utf-8") as fh:
            code = fh.read()
        if "</script" in code.lower():
            raise SystemExit(f"v12/{name} contains a closing script tag")
        parts.append(f"<script>/* ---------- {name} (v12) ---------- */\n{code}\n</script>")
    # Append the beta layer after v12
    for name in BETA_CSS:
        with open(os.path.join(BETA_DIR, name), "r", encoding="utf-8") as fh:
            parts.append(f'<style id="beta-{name[:-4]}">\n{fh.read()}\n</style>')
    for name in BETA_JS:
        with open(os.path.join(BETA_DIR, name), "r", encoding="utf-8") as fh:
            code = fh.read()
        if "</script" in code.lower():
            raise SystemExit(f"beta/{name} contains a closing script tag")
        parts.append(f"<script>/* ---------- beta/{name} ---------- */\n{code}\n</script>")
    idx = html.rindex("</body>")
    html = html[:idx] + "\n".join(parts) + "\n" + html[idx:]
    with open(HTML_OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  built:  {HTML_OUT}  ({len(html):,} chars)")

def main():
    bundle = build_bundle()
    build_html(bundle)
    # Mirror the assets/music directory next to naceca.html so the single-folder
    # delivery works: drop naceca.html + assets/ on a static host and music plays.
    import shutil
    src_music = os.path.join(SRC, "assets", "music")
    if os.path.exists(src_music) and not OUT_DIR:
        dst_music = os.path.join(ROOT, "assets", "music")
        os.makedirs(os.path.dirname(dst_music), exist_ok=True)
        if os.path.exists(dst_music):
            shutil.rmtree(dst_music)
        shutil.copytree(src_music, dst_music)
        total = sum(os.path.getsize(os.path.join(dst_music, f)) for f in os.listdir(dst_music))
        print(f"  music:  {dst_music}  ({total/1024/1024:.1f}MB)")
    # Syntax check the bundle
    rc = os.system(f"node --check {BUNDLE_OUT} 2>&1")
    if rc == 0:
        print("\n  ✓ bundle parses cleanly")
    else:
        print(f"\n  ✗ bundle has syntax errors (exit {rc})")
        raise SystemExit(rc)

if __name__ == "__main__":
    main()
