"""
NACECA build script.

Pipeline:
  1. Concatenate all source modules in dependency order → src/_bundle.js
  2. Inline _bundle.js + styles.css into index.html → naceca.html (single-file build)

Dependency order matters because we use plain <script> globals (no ES modules).
This avoids requiring a webserver — naceca.html runs from any file:// URL.
"""

import os
import re

ROOT = "/home/claude/naceca-modular"
SRC = os.path.join(ROOT, "src")
BUNDLE_OUT = os.path.join(SRC, "_bundle.js")
HTML_IN = os.path.join(ROOT, "index.html")
CSS_IN = os.path.join(ROOT, "styles.css")
HTML_OUT = os.path.join(ROOT, "naceca.html")

# Dependency order — config before systems, engine before scenes, scenes before flow.
LOAD_ORDER = [
    "_HEADER.js",
    # ----- inlined assets (must load before any system that references ASSETS) -----
    "assets/_inline.js",
    # ----- config (data only, no deps) -----
    "config/missions.js",
    "config/skills.js",
    "config/dialogue.js",
    "config/puzzles.js",
    "config/casefile.js",
    "config/evidence_board.js",
    # ----- core systems (state + utils + engine) -----
    "systems/state.js",
    "systems/util.js",
    "systems/state_save.js",
    "systems/audio.js",
    "systems/engine.js",
    # ----- scene helpers -----
    "scenes/_common.js",
    # ----- scenes -----
    "scenes/hq.js",
    "scenes/market.js",
    "scenes/mansion.js",
    "scenes/checkpoint.js",
    "scenes/shrine.js",
    "scenes/asaba.js",
    # ----- gameplay systems -----
    "systems/dialogue_system.js",
    "systems/puzzle_system.js",
    "systems/evidence.js",
    "systems/mission_flow.js",
    "systems/aftermath.js",
    "systems/mission_select.js",
    "systems/skill_tree.js",
    "systems/evidence_board.js",
    "systems/pause.js",
    # ----- entry -----
    "systems/boot.js",
    "main.js",
]

def build_bundle():
    parts = []
    parts.append(
        "/* =========================================================================\n"
        "   NACECA · src/_bundle.js  (auto-generated by build.py — do not edit)\n"
        "   Source modules under config/, systems/, scenes/ — edit those instead.\n"
        "   ========================================================================= */\n\n"
    )
    for rel in LOAD_ORDER:
        path = os.path.join(SRC, rel)
        if not os.path.exists(path):
            print(f"  ! missing {rel}")
            continue
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        parts.append(f"\n/* ---------- {rel} ---------- */\n")
        parts.append(content)
        parts.append("\n")
    bundle = "".join(parts)
    with open(BUNDLE_OUT, "w", encoding="utf-8") as f:
        f.write(bundle)
    print(f"  bundle: {BUNDLE_OUT}  ({len(bundle):,} chars)")
    return bundle

def build_html(bundle):
    with open(HTML_IN, "r", encoding="utf-8") as f:
        html = f.read()
    with open(CSS_IN, "r", encoding="utf-8") as f:
        css = f.read()
    # Inline the CSS — replace the <link> with a <style> block
    html = re.sub(
        r'<link rel="stylesheet" href="styles\.css"\s*/?>',
        lambda m: f"<style>\n{css}\n</style>",
        html,
    )
    # Inline the bundle — replace the <script src="src/_bundle.js"> with a <script>...</script>
    html = re.sub(
        r'<script src="src/_bundle\.js"></script>',
        lambda m: f"<script>\n{bundle}\n</script>",
        html,
    )
    with open(HTML_OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  built:  {HTML_OUT}  ({len(html):,} chars)")

def main():
    bundle = build_bundle()
    build_html(bundle)
    # Mirror the assets/music directory next to naceca.html so the single-folder
    # delivery works: drop naceca.html + assets/ on a static host and music plays.
    import shutil
    src_music = os.path.join(SRC, "assets", "music")
    if os.path.exists(src_music):
        dst_music = os.path.join(ROOT, "assets", "music")
        os.makedirs(os.path.dirname(dst_music), exist_ok=True)
        if os.path.exists(dst_music):
            shutil.rmtree(dst_music)
        shutil.copytree(src_music, dst_music)
        total = sum(os.path.getsize(os.path.join(dst_music, f)) for f in os.listdir(dst_music))
        print(f"  music:  {dst_music}  ({total/1024/1024:.1f}MB)")
    # Syntax check the bundle
    rc = os.system(f"node --check {BUNDLE_OUT} 2>&1")
    if rc == 0:
        print("\n  ✓ bundle parses cleanly")
    else:
        print(f"\n  ✗ bundle has syntax errors (exit {rc})")
        raise SystemExit(rc)

if __name__ == "__main__":
    main()
