"""
Encode src/assets/**/*.png as data URIs into src/assets/_inline.js.

The module exports a single global `ASSETS` object:
  ASSETS.portraits.kelechi  → "data:image/png;base64,iVBORw0..."
  ASSETS.title.naceca_badge → "data:image/png;base64,..."

This keeps the single-file naceca.html self-contained — no external image fetches
needed. Cost is ~50-200KB per portrait × 14 portraits ≈ 1-2MB of inline base64,
which inflates naceca.html from ~240KB to ~3-4MB. Still trivial for a portfolio
piece, and the offline-runnable promise stays intact.
"""
import os
import base64
import json

ROOT = "/home/claude/naceca-modular/src/assets"
OUT = os.path.join(ROOT, "_inline.js")

groups = {}
for sub in sorted(os.listdir(ROOT)):
    full = os.path.join(ROOT, sub)
    if not os.path.isdir(full):
        continue
    g = {}
    for f in sorted(os.listdir(full)):
        if not f.endswith(".png"):
            continue
        path = os.path.join(full, f)
        with open(path, "rb") as fh:
            data = fh.read()
        b64 = base64.b64encode(data).decode("ascii")
        key = os.path.splitext(f)[0]
        g[key] = f"data:image/png;base64,{b64}"
        print(f"  {sub}/{f}  ({len(data):,}B → {len(b64):,}B base64)")
    if g:
        groups[sub] = g

# Emit a JS module — declares a single global `ASSETS`
lines = [
    "/* =========================================================================",
    "   NACECA · src/assets/_inline.js  (auto-generated by encode_assets.py)",
    "   Inlined PNG assets as base64 data URIs. Loaded synchronously from the",
    "   bundle so naceca.html remains a single-file, offline-runnable artifact.",
    "   ========================================================================= */",
    "",
    "const ASSETS = " + json.dumps(groups, indent=2) + ";",
    "",
]
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

total = sum(len(v) for g in groups.values() for v in g.values())
print(f"\n  wrote {OUT}  ({total:,} chars total)")
